### ISSUE TITLE
localhost:3000 say → Invalid email or password

### ISSUE THREAD

**Issue by roboto-cloud** [Dryusdan/Dockerfiles#1]
someone know how run dryusdan/standardnotes and have login and registration feature?
my run script:

**docker run -d -p 3000:3000 dryusdan/standardnotes**

thanks in advance,

**Comment by Dryusdan** [comment]
Hey,
Standardnotes run with standardfiles.
When you register, you use what server domain ?
![screenshot_20171028_173928](https://user-images.githubusercontent.com/4410431/32135929-46c7d5f8-bbf6-11e7-9f2b-b46f8522850a.png) 

:)

**Comment by roboto-cloud** [comment]
hey :) @Dryusdan thanks!!! 
yes I see that here https://github.com/standardfile/ruby-server/wiki/Deploying-a-private-Standard-File-server-using-Docker

could you tell how install the folder extension?

https://github.com/sn-extensions/folders-component

thanks in advance,

**Comment by Dryusdan** [comment]
I keep this idea and try to install folder extension as soon as possible :) (actually I'm work on a light peertube image :) )

**Comment by roboto-cloud** [comment]
@Dryusdan about markdown extension, I don't  found the source, Is possible install it in your  light peertube image??

Regards,

**Comment by Dryusdan** [comment]
In my mind, extension is available on everywhere client if you pay an abonment 🤔
