### ISSUE TITLE
MySql Error

### ISSUE THREAD

**Issue by BobTB** [Dryusdan/Dockerfiles#2]
What I have is this:

![image](https://user-images.githubusercontent.com/15887688/32201753-f8a62408-bdd8-11e7-808c-d85c9de8e698.png)

What are the enviroment variables to set the db location / port? All what I have is:

![image](https://user-images.githubusercontent.com/15887688/32201786-1c1f5152-bdd9-11e7-9715-ccf442f85d24.png)

**Comment by Dryusdan** [comment]
Hum... What image ?

**Comment by BobTB** [comment]
oh :) sorry, the standardfile one

**Comment by Dryusdan** [comment]
Ho... Okay ^^
I use an environment file on this image.
In docker compose I have ` env_file: /standardfiles/.env.app.production` and it file look like 
```
RAILS_ENV=production
SECRET_KEY_BASE=use "bundle exec rake secret"
RAILS_SERVE_STATIC_FILES=true

DB_HOST=yourIPDB_PORT=3306
DB_DATABASE=standardfile
DB_USERNAME=standardfile
DB_PASSWORD=

SALT_PSEUDO_NONCE=(generate token)
```

**Comment by BobTB** [comment]
Ok, got it working. Thx!
