### ISSUE TITLE
Your Docker Automated Builds

### ISSUE THREAD

**Issue by BobTB** [Dryusdan/Dockerfiles#4]
All of your builds are failing now for cca. 10 days. All of them (standardnotes, php-fuelphp, peertube ....). Check them out! Some certificate probloem. I am attaching the image:

![image](https://user-images.githubusercontent.com/15887688/32688551-2ed55cee-c6d3-11e7-84e3-202f36f6910a.png)

**Comment by Dryusdan** [comment]
Houla O.O

Okay... Hum, recently, I've changed my development methods of Docker image on my developpment server. I will deploy this soon on github and docker hub, as soon as I succeed my new CI (actually, this displays my Docker password >< )

**Comment by BobTB** [comment]
Ok...I just forked the simplenotes one and managed to make it work!

**Comment by Dryusdan** [comment]
Ok, hum... I change my repo, image is build in my drone ci, then it push to github to build another by docker hub. Image in Dockerfile repo is not the latest :)
Now, I have multiple repo, one by dockerfile
